# Generated by Django 2.2.28 on 2022-09-18 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0005_auto_20220918_0534'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('accuracy', models.DecimalField(decimal_places=1, max_digits=1)),
                ('cleanliness', models.DecimalField(decimal_places=1, max_digits=1)),
                ('communication', models.DecimalField(decimal_places=1, max_digits=1)),
                ('location', models.DecimalField(decimal_places=1, max_digits=1)),
                ('check_in', models.DecimalField(decimal_places=1, max_digits=1)),
                ('value', models.DecimalField(decimal_places=1, max_digits=1)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
