# Generated by Django 2.2.28 on 2022-09-18 09:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('talks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participants',
            name='actor',
        ),
        migrations.AddField(
            model_name='participants',
            name='actor',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
